name: dotnet

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies (bg)
      run: dotnet restore
      working-directory: ./bg
    - name: Build (bg)
      run: dotnet build --no-restore
      working-directory: ./bg
    - name: Test (bg)
      run: dotnet test --no-build --verbosity normal
      working-directory: ./bg

    - name: Restore dependencies (test)
      run: dotnet restore
      working-directory: ./BlaggenTest
    - name: Build (test)
      run: dotnet build --no-restore
      working-directory: ./BlaggenTest
    - name: Test (test)
      run: dotnet test --no-build --verbosity normal
      working-directory: ./BlaggenTest
